title: Yunliang Zhao's Portfolio
logo: /assets/Profile_Picture.jpg
description: "<a href='/assets/Yunliang_Zhao_Resume.pdf' target='_blank' rel='noopener'> Download My Resume</a>"
show_downloads: false

github:
  is_user_page: false
  is_project_page: false

<nav class="inline-nav">
  <a href="#about-me">About</a> 路
  <a href="#skills">Skills</a> 路
  <a href="#research-experience">Research</a> 路
  <a href="#work-experience">Work</a> 路
  <a href="#leadership">Leadership</a> 路
  <a href="#projects">Projects</a> 路
  <a href="#education">Education</a> 路
  <a href="#honors--awards">Honors</a>
</nav>

theme: jekyll-theme-minimal
